import {lib,game,ui,get,ai,_status} from '../../../../../noname.js'
import { basic } from '../../basic.js';

export let unoConfig = {
    'player_num':{
        name:"游戏人数",
        item:{
            3:'三人',
            4:'四人',
            5:'五人',
            6:'六人',
            7:'七人',
            8:'八人',
            9:'九人',
            10:'十人',
            11:'十一人',
            12:'十二人',
            13:'十三人',
            14:'十四人',
            15:'十五人',
            16:'十六人',
        },
        init:4,
    },
    'plus_rules':{
        name:"罚摸规则",
        intro:`<ul>
        <li><b>质疑规则</b>：+4牌要求在手牌中没有和参照牌同色的牌时才能打出。
        打出时，下家可以选择质疑其是否违规，被质疑需要展示所有手牌。
        质疑成功，则违规者摸四张牌。质疑失败，则质疑者除罚抽的四张牌外额外摸两张牌。</li>
        <li><b>叠加规则</b>：叠加规则下，不限制+4牌的打出。加号牌后可以直接打出加号牌避免罚摸，并叠加罚摸牌数，直到有玩家没有加号牌打出位置，该玩家摸叠加数的牌。</li>
        <li><b>宽松规则</b>：不对+4牌的使用作限制。</li>
        <li><b>严格规则</b>：由系统限制+4牌的使用。</li>
        </ul>`,
        init:'doubt',
        item:{
            "doubt":"质疑规则",
            "add":"叠加规则",
            "loose":"宽松规则",
            "strict":"严格规则",
        },
        onclick:function(item){
            game.saveConfig('plus_rules',item,'uno');
            game.reload();
        }
    },
    'begin_card_count':{
        name:'起始摸牌数',
        init:7,
        item:{
            3:'三张',
            4:'四张',
            5:'五张',
            6:'六张',
            7:'七张',
            8:'八张',
            9:'九张',
            10:'十张',
            11:'十一张',
            12:'十二张',
        },
        onclick:(item)=>{
            game.saveConfig('begin_card_count',item,'uno');
        }
    },
    'win_score':{
        name:'胜利所需积分',
        init:200,
        item:{
            0:'0',
            100:'100',
            200:'200',
            300:'300',
            400:'400',
            500:'500',
            600:'600',
            700:'700',
            800:'800',
            900:'900',
            1000:'1000',
        },
        onclick:(item)=>{
            game.saveConfig('win_score',item,'uno');
        }
    }
};